CHANNELS_TO_USE = [
    {"channel": "30849", "device": "Batterie", "name": "Temperatur", "unit": "C"},
    {
        "channel": "30847",
        "device": "Batterie",
        "name": "Kapazität aktuell",
        "unit": "%",
    },
    {"channel": "30845", "device": "Batterie", "name": "Ladezustand", "unit": "%"},
    {"channel": "31401", "device": "Batterie", "name": "Entladung", "unit": "W"},
    {"channel": "31397", "device": "Batterie", "name": "Ladung", "unit": "W"},
    {
        "channel": "30773",
        "device": "Solar Panele",
        "name": "Leistung String 1",
        "unit": "W",
    },
    {
        "channel": "30961",
        "device": "Solar Panele",
        "name": "Leistung String 2",
        "unit": "W",
    },
    {
        "channel": "30529",
        "device": "Solar Panele",
        "name": "Ertrag gesamt",
        "unit": "W",
    },
    {
        "channel": "30953",
        "device": "SMA Wechselrichter",
        "name": "Temperatur",
        "unit": "C",
    },
    {
        "channel": "30775",
        "device": "Solar Panele",
        "name": "Leistung aktuell",
        "unit": "W",
    },
    {
        "channel": "30867",
        "device": "Netz",
        "name": "Leistung Einspeisung",
        "unit": "W",
    },
    {
        "channel": "30865",
        "device": "Netz",
        "name": "Leistung Bezug",
        "unit": "W",
    },
    {
        "channel": "31395",
        "device": "Batterie",
        "name": "Entladung",
        "unit": "W",
    },
    {
        "channel": "31393",
        "device": "Batterie",
        "name": "Ladung",
        "unit": "W",
    },
    {
        "channel": "30535",
        "device": "Solar Panele",
        "name": "Erzeugung heute",
        "unit": "W",
    },
]
