CHANNELS_TO_USE = [
    {
        "device_name": "Batterie",
        "channels": [31395, 31393, 30849, 30847, 30845],
    },
    {
        "device_name": "Netz",
        "channels": [30865],
    },
    {
        "device_name": "Solaranlage",
        "channels": [30529, 30517, 30867],  # 30775
    },
    {
        "device_name": "SMA Wechselrichter",
        "channels": [30953],
    },
]

CHANNELS_NOT_TO_USE = []


CHANNELS_METADATA = [
    {
        "modbus_channel": "Bat.TmpVal",
        "object_type": "Messwert",
        "name": "Batterietemperatur",
        "read_level": "",
        "group_full": "Batterie > Batterie > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30849",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 10 )",
        "openhab_unit": "%.1f °C",
        "openhab_category": "temperature",
    },
    {
        "modbus_channel": "Operation.EvtCntUsr",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Benutzer",
        "read_level": "",
        "group_full": "Status > Betrieb > Ereignisse fuer Benutzer",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30559",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.EvtCntUsr",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Benutzer",
        "read_level": "",
        "group_full": "Status > Betrieb > Ereignisse fuer Benutzer",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "35377",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.EvtCntIstl",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Installateur",
        "read_level": "",
        "group_full": "Status > Betrieb > Ereignisse fuer Installateur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30561",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.EvtCntIstl",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Installateur",
        "read_level": "",
        "group_full": "Status > Betrieb > Ereignisse fuer Installateur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "35381",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.EvtCntSvc",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Service",
        "read_level": "Svc",
        "group_full": "Status > Betrieb > Ereignisse fuer Service",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30563",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.EvtCntSvc",
        "object_type": "Messwert",
        "name": "Anzahl Ereignisse fuer Service",
        "read_level": "Svc",
        "group_full": "Status > Betrieb > Ereignisse fuer Service",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "35385",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Evt.Dsc",
        "object_type": "Messwert",
        "name": "Fehlerbehebungsmassnahme",
        "read_level": "",
        "group_full": "Status > Betrieb > Aktuelles Ereignis > Fehlerbehebungsmassnahme",
        "possible_values": "885: keine (NoneDsc)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30215",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Evt.EvtNo",
        "object_type": "Messwert",
        "name": "Aktuelle Ereignisnummer fuer Hersteller",
        "read_level": "",
        "group_full": "Status > Betrieb > Aktuelles Ereignis > Ereignisnr. Hersteller",
        "possible_values": "",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30247",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Evt.Msg",
        "object_type": "Messwert",
        "name": "Meldung",
        "read_level": "",
        "group_full": "Status > Betrieb > Aktuelles Ereignis > Meldung",
        "possible_values": "886: keine (NoneMsg)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30213",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Evt.Prio",
        "object_type": "Messwert",
        "name": "Empfohlene Aktion",
        "read_level": "",
        "group_full": "Status > Betrieb > Aktuelles Ereignis > Empfohlene Aktion",
        "possible_values": "336: Hersteller kontaktieren (PrioA)337: Installateur kontaktieren (PrioC)338: ungueltig (PrioIna)887: keine (NonePrio)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30211",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.RmgTms",
        "object_type": "Messwert",
        "name": "Wartezeit bis Einspeisung",
        "read_level": "",
        "group_full": "Status > Betrieb > Wartezeit bis Einspeisung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30199",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "Dauer",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Inverter.Health",
        "object_type": "Messwert",
        "name": "Wechselrichter-Zustand",
        "read_level": "",
        "group_full": "Status > Betrieb > Wechselrichter > Zustand",
        "possible_values": "35: Fehler (Alm)303: Aus (Off)307: Ok (Ok)455: Warnung (Wrn)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32385",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Health",
        "object_type": "Messwert",
        "name": "Zustand",
        "read_level": "",
        "group_full": "Status > Betrieb > Zustand",
        "possible_values": "35: Fehler (Alm)303: Aus (Off)307: Ok (Ok)455: Warnung (Wrn)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30201",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.HealthStt.Alm",
        "object_type": "Messwert",
        "name": "Nennleistung im Zustand Fehler",
        "read_level": "",
        "group_full": "Status > Betrieb > Geraetestatus > Fehler",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30207",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.HealthStt.Ok",
        "object_type": "Messwert",
        "name": "Nennleistung im Zustand Ok",
        "read_level": "",
        "group_full": "Status > Betrieb > Geraetestatus > Ok",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30203",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.HealthStt.Ok",
        "object_type": "Messwert",
        "name": "Nennleistung im Zustand Ok",
        "read_level": "",
        "group_full": "Status > Betrieb > Geraetestatus > Ok",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31085",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.HealthStt.Wrn",
        "object_type": "Messwert",
        "name": "Nennleistung im Zustand Warnung",
        "read_level": "",
        "group_full": "Status > Betrieb > Geraetestatus > Warnung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30205",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "MltFncSw.Stt",
        "object_type": "Messwert",
        "name": "Status des Multifunktionsrelais",
        "read_level": "",
        "group_full": "Geraet > Multifunktionsrelais > Status",
        "possible_values": "303: Aus (Off)308: Ein (On)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30875",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ActlDnsSrvIp",
        "object_type": "Messwert",
        "name": "-",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31041",
        "modbus_address_length": "8",
        "modbus_datatype": "STR32",
        "modbus_dataformat": "UTF8",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ActlGwIp",
        "object_type": "Messwert",
        "name": "-",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31033",
        "modbus_address_length": "8",
        "modbus_datatype": "STR32",
        "modbus_dataformat": "UTF8",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ActlIp",
        "object_type": "Messwert",
        "name": "-",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31017",
        "modbus_address_length": "8",
        "modbus_datatype": "STR32",
        "modbus_dataformat": "UTF8",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ActlSnetMsk",
        "object_type": "Messwert",
        "name": "-",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31025",
        "modbus_address_length": "8",
        "modbus_datatype": "STR32",
        "modbus_dataformat": "UTF8",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocA.ConnSpd",
        "object_type": "Messwert",
        "name": "Verbindungsgeschwindigkeit von SMACOM A",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM A > Verbindungsgeschwindigkeit",
        "possible_values": "302: ------- (None)1720: 10 Mbit/s (ConnSpd10)1721: 100 Mbit/s (ConnSpd100)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30925",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocA.DpxMode",
        "object_type": "Messwert",
        "name": "Duplexmodus von SMACOM A",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM A > Duplexmodus",
        "possible_values": "302: ------- (None)1726: Halbduplex (HalfDpx)1727: Vollduplex (FulDpx)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30927",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocA.Stt",
        "object_type": "Messwert",
        "name": "Speedwire-Verbindungsstatus von SMACOM A",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM A > Status",
        "possible_values": "35: Fehler (Alm)307: Ok (Ok)455: Warnung (Wrn)1725: Keine Verbindung (NotConn)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30929",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocB.ConnSpd",
        "object_type": "Messwert",
        "name": "Verbindungsgeschwindigkeit von SMACOM B",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM B > Verbindungsgeschwindigkeit",
        "possible_values": "302: ------- (None)1720: 10 Mbit/s (ConnSpd10)1721: 100 Mbit/s (ConnSpd100)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30931",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocB.DpxMode",
        "object_type": "Messwert",
        "name": "Duplexmodus von SMACOM B",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM B > Duplexmodus",
        "possible_values": "302: ------- (None)1726: Halbduplex (HalfDpx)1727: Vollduplex (FulDpx)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30933",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Spdwr.ComSocB.Stt",
        "object_type": "Messwert",
        "name": "Speedwire-Verbindungsstatus von SMACOM B",
        "read_level": "",
        "group_full": "Anlagenkommunikation > Speedwire > SMACOM B > Status",
        "possible_values": "35: Fehler (Alm)307: Ok (Ok)455: Warnung (Wrn)1725: Keine Verbindung (NotConn)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30935",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.TmpVal",
        "object_type": "Messwert",
        "name": "Aussentemperatur",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34609",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.TmpVal",
        "object_type": "Messwert",
        "name": "Aussentemperatur",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34625",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.TmpVal",
        "object_type": "Messwert",
        "name": "Aussentemperatur",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34627",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.TmpValMax",
        "object_type": "Messwert",
        "name": "Hoechste gemessene Aussentemperatur",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Hoechste gemessene Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34611",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Mdul.TmpVal",
        "object_type": "Messwert",
        "name": "Modultemperatur",
        "read_level": "",
        "group_full": "Meteorologie > PV-Modul > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34621",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Mdul.TmpVal",
        "object_type": "Messwert",
        "name": "Modultemperatur",
        "read_level": "",
        "group_full": "Meteorologie > PV-Modul > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34629",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Mdul.TmpVal",
        "object_type": "Messwert",
        "name": "Modultemperatur",
        "read_level": "",
        "group_full": "Meteorologie > PV-Modul > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34631",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.HorWSpd",
        "object_type": "Messwert",
        "name": "Windgeschwindigkeit",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Windgeschwindigkeit",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34615",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.HorWSpd",
        "object_type": "Messwert",
        "name": "Windgeschwindigkeit",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Windgeschwindigkeit",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34633",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.HorWSpd",
        "object_type": "Messwert",
        "name": "Windgeschwindigkeit",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Windgeschwindigkeit",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34635",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Env.ExInsol",
        "object_type": "Messwert",
        "name": "Einstrahlung auf externen Sensor",
        "read_level": "",
        "group_full": "Meteorologie > Umgebung > Einstrahlung auf externen Sensor",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34623",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.DyWhOut",
        "object_type": "Messwert",
        "name": "Tagesertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Tagesertrag",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30517",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 1000 )",
        "openhab_unit": "%.1f kWh",
        "openhab_category": "solarplant",
    },
    {
        "modbus_channel": "Metering.DyWhOut",
        "object_type": "Messwert",
        "name": "Tagesertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Tagesertrag",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30535",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 1000 )",
        "openhab_unit": "%.1f kWh",
    },
    {
        "modbus_channel": "Metering.DyWhOut",
        "object_type": "Messwert",
        "name": "Tagesertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Tagesertrag",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30537",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 1000 )",
        "openhab_unit": "%.1f kWh",
    },
    {
        "modbus_channel": "Metering.DyWhOut",
        "object_type": "Messwert",
        "name": "Tagesertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Tagesertrag",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30539",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 1000 )",
        "openhab_unit": "%.1f kWh",
    },
    {
        "modbus_channel": "Metering.GridMs.Hz",
        "object_type": "Messwert",
        "name": "Netzfrequenz",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Netzfrequenz",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31447",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.A.phsA",
        "object_type": "Messwert",
        "name": "Ausgangsstrom Netzeinspeisung Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenstroeme > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31435",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.A.phsB",
        "object_type": "Messwert",
        "name": "Ausgangsstrom Netzeinspeisung Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenstroeme > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31437",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.A.phsC",
        "object_type": "Messwert",
        "name": "Ausgangsstrom Netzeinspeisung Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenstroeme > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31439",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsA2B",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L1 gegen L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L1 gegen L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31451",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsB2C",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L2 gegen L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L2 gegen L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31453",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsC2A",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L3 gegen L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L3 gegen L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31449",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsA",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31253",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsB",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31255",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.PhV.phsC",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Phasenspannungen > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31257",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.W.phsA",
        "object_type": "Messwert",
        "name": "Leistung Netzeinspeisung L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Wirkleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31259",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.W.phsB",
        "object_type": "Messwert",
        "name": "Leistung Netzeinspeisung L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Wirkleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31261",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.W.phsC",
        "object_type": "Messwert",
        "name": "Leistung Netzeinspeisung L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Wirkleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31263",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.WIn.phsA",
        "object_type": "Messwert",
        "name": "Leistung Netzbezug Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > aufgenommene Wirkleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31265",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.WIn.phsB",
        "object_type": "Messwert",
        "name": "Leistung Netzbezug Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > aufgenommene Wirkleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31267",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.WIn.phsC",
        "object_type": "Messwert",
        "name": "Leistung Netzbezug Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > aufgenommene Wirkleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31269",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VAr.phsA",
        "object_type": "Messwert",
        "name": "Blindleistung Netzeinspeisung Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Blindleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31271",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VAr.phsB",
        "object_type": "Messwert",
        "name": "Blindleistung Netzeinspeisung Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Blindleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31273",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VAr.phsC",
        "object_type": "Messwert",
        "name": "Blindleistung Netzeinspeisung Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Blindleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31275",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotVAr",
        "object_type": "Messwert",
        "name": "Blindleistung Netzeinspeisung",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Blindleistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31277",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VA.phsA",
        "object_type": "Messwert",
        "name": "Scheinleistung L1",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Scheinleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31441",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VA.phsB",
        "object_type": "Messwert",
        "name": "Scheinleistung L2",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Scheinleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31443",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.VA.phsC",
        "object_type": "Messwert",
        "name": "Scheinleistung L3",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Scheinleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31445",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotVA",
        "object_type": "Messwert",
        "name": "Scheinleistung",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Scheinleistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31455",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotPF",
        "object_type": "Messwert",
        "name": "Verschiebungsfaktor",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Verschiebungsfaktor",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31433",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotPFEEI",
        "object_type": "Messwert",
        "name": "EEI-Verschiebungsfaktor",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > EEI-Verschiebungsfaktor",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31499",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotWOut",
        "object_type": "Messwert",
        "name": "Netzeinspeisung",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Eingespeiste Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30867",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
        "openhab_category": "solarplant",
    },
    {
        "modbus_channel": "Metering.GridMs.TotWOut",
        "object_type": "Messwert",
        "name": "Leistung Einspeisung",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Eingespeiste Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32341",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
    },
    {
        "modbus_channel": "Metering.GridMs.TotWhOut",
        "object_type": "Messwert",
        "name": "Zaehlerstand Einspeisezaehler",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Gesamtertrag",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30583",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.GridMs.TotWIn",
        "object_type": "Messwert",
        "name": "Leistung Bezug",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Aufgenommene Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30865",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
    },
    {
        "modbus_channel": "Metering.GridMs.TotWhIn",
        "object_type": "Messwert",
        "name": "Zaehlerstand Bezugszaehler",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Netzmessungen > Aufgenommene Energie",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30581",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.ChaCtlComAval",
        "object_type": "Messwert",
        "name": "Steuerung der Batterieladung ueber Kommunikation verfuegbar",
        "read_level": "",
        "group_full": "Batterie > Batterie > Steuerung der Ladung ueber Kommunikation verfuegbar",
        "possible_values": "1129: Ja (Yes)1130: Nein (No)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31061",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.ChaCtlComAval",
        "object_type": "Messwert",
        "name": "Steuerung der Batterieladung ueber Kommunikation verfuegbar",
        "read_level": "",
        "group_full": "Batterie > Batterie > Steuerung der Ladung ueber Kommunikation verfuegbar",
        "possible_values": "1129: Ja (Yes)1130: Nein (No)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34669",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.CmpBMS.OpStt",
        "object_type": "Messwert",
        "name": "Betriebsstatus",
        "read_level": "",
        "group_full": "Batterie > Betrieb > Batteriemanagementsystem > Allgemeiner Betriebszustand",
        "possible_values": "71: Geraetestoerung (DevFlt)303: Aus (Off)388: Status Betrieb (SttOp)1295: Standby (Stdby)2291: Batterie Standby (BatWait)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34659",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Bat.Health",
        "object_type": "Messwert",
        "name": "Batterie-Zustand",
        "read_level": "",
        "group_full": "Status > Betrieb > Batterie > Zustand",
        "possible_values": "35: Fehler (Alm)303: Aus (Off)307: Ok (Ok)455: Warnung (Wrn)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31391",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "CmpBMS.GetBatChaWh",
        "object_type": "Messwert",
        "name": "Aktuelle Ladeenergie",
        "read_level": "",
        "group_full": "Batterie > Batteriemanagementsystem > Aktuelle Ladeenergie",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32201",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "CmpBMS.GetBatDschWh",
        "object_type": "Messwert",
        "name": "Aktuelle Entladeenergie",
        "read_level": "",
        "group_full": "Batterie > Batteriemanagementsystem > Aktuelle Entladeenergie",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32205",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.ChaVolSptDmd",
        "object_type": "Messwert",
        "name": "Ladeschlussspannung",
        "read_level": "",
        "group_full": "Batterie > Batterie > Ladeschlussspannung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32239",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.DschVolSptDmd",
        "object_type": "Messwert",
        "name": "Entladeschlussspannung",
        "read_level": "",
        "group_full": "Batterie > Batterie > Entladeschlussspannung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32245",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.ChaAmpSptDmd",
        "object_type": "Messwert",
        "name": "Maximaler Ladestrom",
        "read_level": "",
        "group_full": "Batterie > Batterie > Maximaler Ladestrom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32251",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.Diag.ActlCapacNom",
        "object_type": "Messwert",
        "name": "Aktuelle Batteriekapazitaet",
        "read_level": "",
        "group_full": "Batterie > Batterie > Diagnose > Aktuelle Kapazitaet",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30847",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_category": "battery",
    },
    {
        "modbus_channel": "Operation.ComRsTms",
        "object_type": "Messwert",
        "name": "Verbleibende Lauzeit bis KP Neustart",
        "read_level": "",
        "group_full": "Externe Kommunikation > Betrieb > Verbleibende Lauzeit bis KP Neustart",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32405",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "HIDDEN",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "BatChrg.BatChrg",
        "object_type": "Messwert",
        "name": "Batterieladung",
        "read_level": "",
        "group_full": "Batterie > Batterieladung > Batterieladung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31397",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "BatDsch.BatDsch",
        "object_type": "Messwert",
        "name": "Batterieentladung",
        "read_level": "",
        "group_full": "Batterie > Batterieentladung > Batterieentladung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31401",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.TotWhOut",
        "object_type": "Messwert",
        "name": "Gesamtertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Gesamtertrag",
        "possible_values": "Wh (64 Bit)",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30513",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.TotWhOut",
        "object_type": "Messwert",
        "name": "Gesamtertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Gesamtertrag",
        "possible_values": "Wh (32 Bit)",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30529",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_transformation": "JS( | parseFloat(input) / 1000 )",
        "openhab_unit": "%.1f kWh",
        "openhab_category": "solarplant",
    },
    {
        "modbus_channel": "Metering.TotWhOut",
        "object_type": "Messwert",
        "name": "Gesamtertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Gesamtertrag",
        "possible_values": "kWh (32 Bit)",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30531",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Metering.TotWhOut",
        "object_type": "Messwert",
        "name": "Gesamtertrag",
        "read_level": "",
        "group_full": "AC-Seite > Messwerte > Gesamtertrag",
        "possible_values": "MWh (32 Bit)",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30533",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.Amp",
        "object_type": "Messwert",
        "name": "Batteriestrom",
        "read_level": "",
        "group_full": "Batterie > Batterie > Strom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30843",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.ChaStt",
        "object_type": "Messwert",
        "name": "Aktueller Batterieladezustand",
        "read_level": "",
        "group_full": "Batterie > Batterie > Ladezustand",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30845",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%d%%",
        "openhab_category": "batterylevel",
    },
    {
        "modbus_channel": "Bat.OpStt",
        "object_type": "Messwert",
        "name": "Betriebsstatus der Batterie",
        "read_level": "",
        "group_full": "Batterie > Batterie > Allgemeiner Betriebszustand",
        "possible_values": "303: Aus (Off)2291: Batterie Standby (BatWait)3664: Notladebetrieb (EmgCha)2292: Batterie laden (BatChaStt)2293: Batterie entladen (BatDschStt)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30955",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.DschAmpSptDmd",
        "object_type": "Messwert",
        "name": "Maximaler Entladestrom",
        "read_level": "",
        "group_full": "Batterie > Batterie > Maximaler Entladestrom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "32257",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Bat.Vol",
        "object_type": "Messwert",
        "name": "Batteriespannung",
        "read_level": "",
        "group_full": "Batterie > Batterie > Spannung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30851",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "BatChrg.CurBatCha",
        "object_type": "Messwert",
        "name": "Momentane Batterieladung",
        "read_level": "",
        "group_full": "Batterie > Batterieladung > Momentane Batterieladung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31393",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
        "openhab_category": "battery",
    },
    {
        "modbus_channel": "BatChrg.ActBatChrg",
        "object_type": "Messwert",
        "name": "Ladung der aktuellen Batterie",
        "read_level": "",
        "group_full": "Batterie > Batterieladung > Ladung der aktuellen Batterie",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34661",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "BatDsch.ActBatDsch",
        "object_type": "Messwert",
        "name": "Batterieentladung der aktuellen Batterie",
        "read_level": "",
        "group_full": "Batterie > Batterieentladung > Entladung der aktuellen Batterie",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34665",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "BatDsch.CurBatDsch",
        "object_type": "Messwert",
        "name": "Momentane Batterieentladung",
        "read_level": "",
        "group_full": "Batterie > Batterieentladung > Momentane Batterieentladung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31395",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
        "openhab_category": "battery",
    },
    {
        "modbus_channel": "BatUsDm.Stt",
        "object_type": "Messwert",
        "name": "Status Batterienutzungsbereich",
        "read_level": "",
        "group_full": "Batterie > Nutzungsbereiche > Status",
        "possible_values": "2614: Eigenverbrauchsbereich (SelfCsmpDm)2615: Ladezustanderhaltungsbereich (ChaSttDm)2616: Ersatzstrombereich (BckDm)2617: Tiefentladeschutzbereich (DschProDm)2618: Tiefentladebereich (ExhDschDm)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31057",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Coolsys.Cab.TmpVal",
        "object_type": "Messwert",
        "name": "Innentemperatur",
        "read_level": "Svc",
        "group_full": "Geraet > Kuehlsystem > Innenraum > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30953",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
        "openhab_unit": "%.1f °C",
        "openhab_transformation": "JS( | parseFloat(input) / 10 )",
        "openhab_category": "temperature",
    },
    {
        "modbus_channel": "Coolsys.Cab.TmpVal",
        "object_type": "Messwert",
        "name": "Innentemperatur",
        "read_level": "Svc",
        "group_full": "Geraet > Kuehlsystem > Innenraum > Temperatur",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "34113",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "TEMP",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Amp",
        "object_type": "Messwert",
        "name": "DC Strom Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Strom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30769",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Amp",
        "object_type": "Messwert",
        "name": "DC Strom Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Strom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30957",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Amp",
        "object_type": "Messwert",
        "name": "DC Strom Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Strom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31793",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Amp",
        "object_type": "Messwert",
        "name": "DC Strom Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Strom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31795",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Vol",
        "object_type": "Messwert",
        "name": "DC Spannung Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Spannung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30771",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Vol",
        "object_type": "Messwert",
        "name": "DC Spannung Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Spannung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30959",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Watt",
        "object_type": "Messwert",
        "name": "DC Leistung Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30773",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DcMs.Watt",
        "object_type": "Messwert",
        "name": "DC Leistung Eingang",
        "read_level": "",
        "group_full": "DC-Seite > DC Messungen > Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30961",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridGuard.Cntry",
        "object_type": "Messwert",
        "name": "Eingestellter Laenderdatensatz",
        "read_level": "",
        "group_full": "Netzueberwachung > Netzueberwachung > Laenderdatensatz",
        "possible_values": "27: Sondereinstellung (Adj)333: [GR] PPC (PPC)438: [DE] VDE0126-1-1 (VDE0126-1-1)1199: [CZ] PPDS (PPDS)7538: [IL] SI4777_HS131_13 (SI4777_HS131_13)7539: [ES] RD1699/413 (RD1699/413)7549: [AU] AS4777.2_2015 (AS4777.2_2015)7550: [ZA] NRS 097-2-1 (NRS97-2-1)7551: [CL] NT_Ley20571 (NT_Ley2057)7556: [TH] MEA2016 (MEA2016)7557: [TH] PEA2016 (PEA2016)7565: [BR] ABNT NBR 16149:2013 (ABNT_NBR_16149_2013)7584: [DE] VDE-AR-N4105:2018 Erzeuger >4,6 kVA (VDEARN4105/18a)7590: [EU] EN50549-1:2018 LV (EN50549-1/18)7592: SMA Default 2019 50Hz (DftSMA/19)7594: [GB] ENA-EREC-G98/1:2018 (ENA-G98/1/18)7595: [GB] ENA-EREC-G99/1:2018 (ENA-G99/1/18)7599: [DK] Dansk Energi DK1:2019 LV (DK1-West/19)7600: [DK] Dansk Energi DK2:2019 LV (DK2-East/19)7602: [BE] C10/11:2019 LV Erzeuger int. EKS (BE-C10/11/19-09 PV_a)7603: [BE] C10/11:2019 LV Erzeuger ext. EKS (BE-C10/11/19-09 PV_b)7610: [IT] CEI0-21:2019 Anlage \u226411,08 kW (IT-CEI0-21/19_a)7612: [IT] CEI0-21:2019 Anlage >11,08 kW (IT-CEI0-21/19_c)7615: [AT] TOR Erzeuger Typ A V1.0:2019 (AT-TOR-Erzeuger-A/19_b)7618: [FR] VFR:2019 (VFR2019)7620: [IN] IEC 61727 (IEC61727_IN)7623: [FI] VJV:2018 (VJV2018)7636: [CH] NA/EEA-NE7:2020 Erzeuger \u2264 250 kW (NA-EEA-NE7_1)7637: [CH] NA/EEA-NE7:2020 Speicher \u2264 250 kW (NA-EEA-NE7_1a)7658: [PL] PN-EN 50549-1:2019 (PN-EN_50549-1_2019)7659: [PL] PN-EN 50549-1:2019_1ph (PN-EN_50549-1_2019_1ph)7660: [PL] PN-EN 50549-2:2019 (PN-EN_50549-2_2019)7661: [AU] AS/NZS 4777.2:2020 Erzeuger Reg. A (AS-NZS-4777-2_1)7662: [AU] AS/NZS 4777.2:2020 Erzeuger Reg. B (AS-NZS-4777-2_1a)7663: [AU] AS/NZS 4777.2:2020 Erzeuger Reg. C (AS-NZS-4777-2_1b)7664: [AU] AS/NZS 4777.2:2020 Erzeuger Reg. NZ (AS-NZS-4777-2_1c)7665: [AU] AS/NZS 4777.2:2020 Speicher Reg. A (AS-NZS-4777-2_1d)7666: [AU] AS/NZS 4777.2:2020 Speicher Reg. B (AS-NZS-4777-2_1e)7667: [AU] AS/NZS 4777.2:2020 Speicher Reg. C (AS-NZS-4777-2_1f)7668: [AU] AS/NZS 4777.2:2020 Speicher Reg. NZ (AS-NZS-4777-2_1g)7671: [SE] EIFS-2018:2 Erzeuger Typ A < 1,5 MW (EIFS-2018_1)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "40109",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.A.phsA",
        "object_type": "Messwert",
        "name": "Netzstrom Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenstroeme > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30977",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.A.phsB",
        "object_type": "Messwert",
        "name": "Netzstrom Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenstroeme > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30979",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.A.phsC",
        "object_type": "Messwert",
        "name": "Netzstrom Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenstroeme > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30981",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.Hz",
        "object_type": "Messwert",
        "name": "Netzfrequenz",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Netzfrequenz",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30803",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsA",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30783",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsA2B",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L1 gegen L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L1 gegen L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30789",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsB",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30785",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsB2C",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L2 gegen L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L2 gegen L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30791",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsC",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30787",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.PhV.phsC2A",
        "object_type": "Messwert",
        "name": "Netzspannung Phase L3 gegen L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Phasenspannungen > Phase L3 gegen L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,01",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30793",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX2",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotA",
        "object_type": "Messwert",
        "name": "Netzstrom",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Strom Summe aller Phasen",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30795",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotPFEEI",
        "object_type": "Messwert",
        "name": "EEI-Verschiebungsfaktor",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > EEI-Verschiebungsfaktor",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31221",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotPFPrc",
        "object_type": "Messwert",
        "name": "Verschiebungsfaktor",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Verschiebungsfaktor",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30949",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotVA",
        "object_type": "Messwert",
        "name": "Scheinleistung",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Scheinleistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30813",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotVAr",
        "object_type": "Messwert",
        "name": "Blindleistung",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Blindleistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31497",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.TotW",
        "object_type": "Messwert",
        "name": "Aktuell erzeugte Leistung",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Leistung",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30775",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
        "openhab_unit": "%.1f W",
    },
    {
        "modbus_channel": "GridMs.VA.phsA",
        "object_type": "Messwert",
        "name": "Scheinleistung L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Scheinleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30815",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.VA.phsB",
        "object_type": "Messwert",
        "name": "Scheinleistung L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Scheinleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30817",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.VA.phsC",
        "object_type": "Messwert",
        "name": "Scheinleistung L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Scheinleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30819",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.VAr.phsA",
        "object_type": "Messwert",
        "name": "Blindleistung L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Blindleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30807",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.VAr.phsB",
        "object_type": "Messwert",
        "name": "Blindleistung L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Blindleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30809",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.VAr.phsC",
        "object_type": "Messwert",
        "name": "Blindleistung L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Blindleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30811",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.W.phsA",
        "object_type": "Messwert",
        "name": "Leistung L1",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Wirkleistung > Phase L1",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30777",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.W.phsB",
        "object_type": "Messwert",
        "name": "Leistung L2",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Wirkleistung > Phase L2",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30779",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "GridMs.W.phsC",
        "object_type": "Messwert",
        "name": "Leistung L3",
        "read_level": "",
        "group_full": "AC-Seite > Netzmessungen > Wirkleistung > Phase L3",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30781",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Isolation.FltA",
        "object_type": "Messwert",
        "name": "Fehlerstrom",
        "read_level": "",
        "group_full": "DC-Seite > Isolationsueberwachung > Fehlerstrom",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "0,001",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31247",
        "modbus_address_length": "2",
        "modbus_datatype": "S32",
        "modbus_dataformat": "FIX3",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Isolation.LeakRis",
        "object_type": "Messwert",
        "name": "Isolationswiderstand",
        "read_level": "",
        "group_full": "DC-Seite > Isolationsueberwachung > Isolationswiderstand",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30225",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Bat.Health",
        "object_type": "Messwert",
        "name": "Batterie-Zustand",
        "read_level": "",
        "group_full": "Status > Betrieb > Batterie > Zustand",
        "possible_values": "35: Fehler (Alm)303: Aus (Off)307: Ok (Ok)455: Warnung (Wrn)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "31391",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.Evt.EvtNo",
        "object_type": "Messwert",
        "name": "Aktuelle Ereignisnummer fuer Hersteller",
        "read_level": "",
        "group_full": "Status > Betrieb > Aktuelles Ereignis > Ereignisnr. Hersteller",
        "possible_values": "",
        "default_value": "-",
        "step_size": "1",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30247",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.GriSwStt",
        "object_type": "Messwert",
        "name": "Netzrelais und -schuetz",
        "read_level": "",
        "group_full": "Status > Betrieb > Status des Netzrelais",
        "possible_values": "51: Geschlossen (Cls)311: Offen (Opn)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30217",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.OpStt",
        "object_type": "Messwert",
        "name": "Allgemeiner Betriebszustand",
        "read_level": "",
        "group_full": "Status > Betrieb > Allgemeiner Betriebszustand",
        "possible_values": "303: Aus (Off)569: Eingeschaltet (Run)1295: Standby (Stdby)1795: Verriegelt (Lok)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "40029",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.PvGriConn",
        "object_type": "Messwert",
        "name": "Netzanbindung der Anlage",
        "read_level": "",
        "group_full": "AC-Seite > Betrieb > Netzanbindung",
        "possible_values": "1779: Getrennt (Dscon)1780: \u00d6ffentliches Stromnetz (PubGri)1781: Inselnetz (IsoGri)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30881",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.RunStt",
        "object_type": "Messwert",
        "name": "Betriebsstatus",
        "read_level": "",
        "group_full": "Status > Betrieb > Betriebsstatus",
        "possible_values": "235: Netzparallelbetrieb (GriOp)1463: Backup (Bck)1469: Herunterfahren (Shtdwn)2119: Abregelung (Drt)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "33003",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Operation.RstrLokStt",
        "object_type": "Messwert",
        "name": "Verriegelungsstatus",
        "read_level": "",
        "group_full": "Status > Betrieb > Verriegelungsstatus",
        "possible_values": "257: Frequenz unzulaessig (HzFlt)1655: Lichtbogen erkannt (EvtAfci)1690: Schnellabschaltung (FstStop)2386: \u00dcberspannung (OvVol)2387: Unterspannung (UnVol)2388: \u00dcberfrequenz (OvHz)2389: Unterfrequenz (UnHz)2390: Passive Inselnetzerkennung (PID)2490: Phasenausfall (PLD)3165: PLL-Fehler (PLL)3166: Phasenausfall niederspannungsseitig (PLDLoVol)3167: Aktive Inselnetzerkennung (ActIsldDet)4553: Nach Fehlerstrom (ManRstrRCD)4570: Warte auf Betriebsfreigabe (WaitStr)16777213: Information liegt nicht vor (NaNStt)",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30251",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "-",
        "object_type": "Messwert",
        "name": "Versionsnummer SMA Modbus-Profil",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30001",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "RAW",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Nameplate.SusyId",
        "object_type": "Messwert",
        "name": "SUSyID Modul",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30003",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "RAW",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "Nameplate.SerNum",
        "object_type": "Messwert",
        "name": "Seriennummer",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30005",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "RAW",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "-",
        "object_type": "Messwert",
        "name": "Unit ID des Wechselrichters",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "42109",
        "modbus_address_length": "4",
        "modbus_datatype": "U64",
        "modbus_dataformat": "RAW",
        "modbus_access": "RW",
    },
    {
        "modbus_channel": "-",
        "object_type": "Messwert",
        "name": "SMA Grid Guard-Code",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "43090",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "FIX0",
        "modbus_access": "RW",
    },
    {
        "modbus_channel": "Nameplate.Vendor",
        "object_type": "Messwert",
        "name": "Hersteller",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30055",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "TAGLIST",
        "modbus_access": "RO",
    },
    {
        "modbus_channel": "DtTm.Tm",
        "object_type": "Messwert",
        "name": "Systemzeit",
        "read_level": "-",
        "group_full": "-",
        "possible_values": "-",
        "default_value": "-",
        "step_size": "-",
        "write_level": "-",
        "grid_guard": "-",
        "modbus_address": "30193",
        "modbus_address_length": "2",
        "modbus_datatype": "U32",
        "modbus_dataformat": "DT",
        "modbus_access": "RO",
    },
]


RAW_KEYS = [
    "6100_004F4E00",
    "6800_0883D800",
    "6100_002F7A00",
    "6800_0883D900",
    "6400_00432200",
    "6400_00496700",
    "6400_00496800",
    "6100_00295A00",
    "6180_08495E00",
    "6100_00496900",
    "6100_00496A00",
    "6100_00696E00",
    "6800_08A33A00",
    "6800_008AA200",
    "6100_40263F00",
    "6100_0046C200",
    "6800_00832A00",
    "6180_08214800",
    "6180_08414900",
    "6180_08412B00",
    "6400_00462500",
    "6400_00462400",
    "6100_40463700",
    "6100_40463600",
    "6800_08862500",
    "6182_08434C00",
    "6100_4046F200",
    "6180_08412800",
    "6400_00260100",
    "6100_402F2000",
    "6100_402F1E00",
    "6800_088F2000",
    "6800_088F2100",
    "6800_10852400",
    "6800_00853400",
    "6180_08652600",
    "6800_00852F00",
    "6180_08652400",
    "6180_08653A00",
    "6100_00653100",
    "6100_00653200",
    "6800_08811F00",
    "6400_00462E00",
    "6800_08839500",
]

RAW_KEYS_MAPPING = [
    {"key": "6100_0046C200", "name": "Solarleistung aktuell"},
    {"key": "6100_00496A00", "name": "Batterie-Entladung aktuell"},
    {"key": "6100_40263F00", "name": "Hausverbrauch aktuell"},
    {"key": "6400_00260100", "name": "Ertrag gesamt"},
    {"key": "6400_00462500", "name": "Bezug Energie vom Netz gesamt"},
    {"key": "6400_00462400", "name": "Einspeisung Energie ins Netz gesamt"},
    {"key": "6100_00295A00", "name": "Batterie Level aktuell"},
    {"key": "6400_00496700", "name": "Batterie Ladung aktuell"},
    {"key": "6400_00496800", "name": "Batterie Entladung aktuell"},
]
