id: solar_fetch_data
namespace: rui.solar

tasks:
  - id: file_system
    type: io.kestra.plugin.core.flow.WorkingDirectory

    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/rui1610/solar
        branch: main
        username: rui1610
        password: "{{ kv('GITHUB_PAT') }}"

      - id: fetch_raw_data
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: ghcr.io/kestra-io/pydata:latest
        env:
          TZ: Europe/Berlin
        beforeCommands:
          - pip install -r .devcontainer/requirements.txt
          - export SMA_INVERTER_IP={{ kv('SMA_INVERTER_IP') }}
          - export SMA_INVERTER_PORT={{ kv('SMA_INVERTER_PORT') }}
        commands:
          - python fetch_raw_data.py

      - id: commit_and_push_new_data
        type: io.kestra.plugin.git.Push
        branch: main
        username: rui1610
        password: "{{ kv('GITHUB_PAT') }}"
        commitMessage: "updated measurement data {{ now() }}"

triggers:
  - id: expression_trigger_1
    type: io.kestra.plugin.core.trigger.Schedule
    # This is a cron expression that runs every day at 22:00
    cron: "00 22 * * *"
  - id: expression_trigger_2
    type: io.kestra.plugin.core.trigger.Schedule
    # This is a cron expression that runs every day at 23:00
    cron: "00 23 * * *"   
  - id: expression_trigger_3
    type: io.kestra.plugin.core.trigger.Schedule
    # This is a cron expression that runs every day at 23:58
    cron: "58 23 * * *"
  - id: expression_trigger_4
    type: io.kestra.plugin.core.trigger.Schedule
    # This is a cron expression that runs every day at 23:59
    cron: "59 23 * * *"
